Oneway sprite
TMB-Barcelona/TMB-Icons pull request #1
Opened 2019-11-21 17:27 UTC by fpsampayo

adds oneway arrow sprite

2019-11-21 18:05 UTC, oscarfonts requested changes
Genera por favor el PNG y actualiza el index.html (ver readme).

2019-11-21 18:05 UTC, oscarfonts commented on package.json
> +    "@mapbox/spritezero-cli": "geomatico/spritezero-cli",
Me temo que si abrimos PR contra mapbox/spritezero-cli no va a servir de nada, no?

2019-11-22 12:05 UTC, fpsampayo commented on package.json
> +    "@mapbox/spritezero-cli": "geomatico/spritezero-cli",
Una imagen vale más que mil palabras...
https://github.com/mapbox/spritezero-cli/pulls

2019-11-22 17:37 UTC, oscarfonts approved these changes

2019-11-22 17:38 UTC, merged

2019-11-22 17:38 UTC, oscarfonts commented
Gracias!